/**
 * Builds an {@link ExemplarBundle} from the golden matcher fixture.
 *
 * The fixture carries the *same* float32-quantized coordinates the exporter would write,
 * so a matcher exercised through this bundle is exercised through the real code path —
 * flat payload, offsets and all — rather than through a test-only shortcut.
 */

import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

import type { Handedness, HandLandmarks } from '../../src/domain/landmarks/types';
import { handLandmarks } from '../../src/domain/landmarks/types';
import type { ExemplarBundle, ExemplarHand, PoseEntry } from '../../src/domain/recognition/types';

/** One exemplar or probe hand as the fixture stores it. */
export interface FixtureHand {
  handedness: Handedness;
  landmarks: [number, number, number][];
}

/** The matcher fixture document. */
export interface MatcherFixture {
  tolerance_relative: number;
  softmax_temperature: number;
  weights: number[];
  poses: {
    pose_id: string;
    required_hands: number;
    exemplars: { sample_id: string; hands: FixtureHand[] }[];
  }[];
  cases: {
    name: string;
    source_pose_id: string;
    hands: FixtureHand[];
    candidates: { pose_id: string; distance: number; confidence: number }[];
  }[];
}

/** Read the fixture generated by `scripts/export_web_fixtures.py`. */
export function readMatcherFixture(): MatcherFixture {
  return JSON.parse(
    readFileSync(resolve(__dirname, '../fixtures/matcher_cases.json'), 'utf-8'),
  ) as MatcherFixture;
}

/** Turn a fixture hand's coordinate triples into {@link HandLandmarks}. */
export function toHandLandmarks(hand: FixtureHand): HandLandmarks {
  return handLandmarks(hand.landmarks.map(([x, y, z]) => ({ x, y, z })));
}

/**
 * Assemble the fixture's exemplars into a bundle, laid out exactly as the exporter does:
 * poses in order, hands in order, 21 × 3 floats each.
 */
export function bundleFromFixture(fixture: MatcherFixture): ExemplarBundle {
  const landmarkCount = 21;
  const components = 3;
  const floatsPerHand = landmarkCount * components;

  const totalHands = fixture.poses.reduce(
    (total, pose) => total + pose.exemplars.reduce((n, sample) => n + sample.hands.length, 0),
    0,
  );
  const data = new Float32Array(totalHands * floatsPerHand);

  let handIndex = 0;
  const poses: PoseEntry[] = fixture.poses.map((pose) => {
    const hands: ExemplarHand[] = [];
    for (const sample of pose.exemplars) {
      for (const hand of sample.hands) {
        const offset = handIndex * floatsPerHand;
        hand.landmarks.forEach(([x, y, z], i) => {
          data[offset + i * components] = x;
          data[offset + i * components + 1] = y;
          data[offset + i * components + 2] = z;
        });
        hands.push({ sampleId: sample.sample_id, handedness: hand.handedness, offset });
        handIndex += 1;
      }
    }
    return {
      poseId: pose.pose_id,
      displayName: pose.pose_id,
      requiredHands: pose.required_hands,
      sampleCount: pose.exemplars.length,
      hands,
    };
  });

  return {
    formatVersion: 1,
    datasetFingerprint: 'sha256:fixture',
    generatedAt: '2026-08-20T00:00:00Z',
    normalization: { strategy: 'translation_scale', version: '1.0' },
    minSamples: 20,
    landmarkCount,
    components,
    totalHands,
    catalogPoseCount: fixture.poses.length,
    poses,
    excluded: [],
    data,
  };
}
