"""FR-081/FR-084 as an executable assertion: the same dataset, the same bundle.

Determinism is not a nicety here. The bundle is a build artifact regenerated by whoever
happens to run the export, and a payload whose bytes drift between machines or Python
versions would make "is this bundle stale?" unanswerable — which is precisely what
``dataset_fingerprint`` exists to answer.

The payload and the fingerprint must be **byte-identical** across runs. The manifest is
compared byte-for-byte with one deliberate exception: ``generated_at`` is provenance, is
excluded from the fingerprint by design, and would otherwise make this test fail or pass
depending on which side of a second boundary the two runs landed. Excluding it here is the
same decision the exporter documents, asserted rather than assumed.
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

import pytest

from scripts.export_web_exemplars import build_bundle, serialize_manifest

REPO_ROOT = Path(__file__).resolve().parents[2]
DATASET = REPO_ROOT / "datasets"
EXPORT_SCRIPT = REPO_ROOT / "scripts" / "export_web_exemplars.py"

pytestmark = pytest.mark.skipif(
    not (DATASET / "poses").is_dir(), reason="repository dataset not present"
)


def _without_timestamp(manifest_text: str) -> str:
    manifest = json.loads(manifest_text)
    manifest["generated_at"] = "<excluded from the fingerprint by design>"
    return json.dumps(manifest, indent=2, ensure_ascii=False)


def test_two_in_memory_builds_agree_byte_for_byte() -> None:
    first_manifest, first_payload = build_bundle(DATASET)
    second_manifest, second_payload = build_bundle(DATASET)

    assert first_payload == second_payload
    assert first_manifest["dataset_fingerprint"] == second_manifest["dataset_fingerprint"]
    assert _without_timestamp(serialize_manifest(first_manifest)) == _without_timestamp(
        serialize_manifest(second_manifest)
    )


def test_two_runs_of_the_script_produce_identical_files(tmp_path: Path) -> None:
    """The claim is about the *script's output on disk*, not only its return values."""
    outputs = []
    for run in ("a", "b"):
        out_dir = tmp_path / run
        result = subprocess.run(
            [
                sys.executable,
                str(EXPORT_SCRIPT),
                "--dataset-root",
                str(DATASET),
                "--out-dir",
                str(out_dir),
            ],
            cwd=str(REPO_ROOT),
            capture_output=True,
            text=True,
            check=False,
        )
        assert result.returncode == 0, result.stderr
        outputs.append(out_dir)

    first, second = outputs
    assert (first / "exemplars.bin").read_bytes() == (second / "exemplars.bin").read_bytes()
    assert _without_timestamp(
        (first / "exemplars.manifest.json").read_text(encoding="utf-8")
    ) == _without_timestamp((second / "exemplars.manifest.json").read_text(encoding="utf-8"))


def test_the_exclusion_is_reported_not_hidden() -> None:
    """FR-023a/FR-085: a pose below the minimum is named, counted, and given a reason."""
    manifest, _ = build_bundle(DATASET)
    excluded = manifest["excluded"]
    assert isinstance(excluded, list)
    assert excluded, "the repository dataset has one pose below the minimum"

    by_id = {entry["pose_id"]: entry for entry in excluded}
    assert "domain_expansion" in by_id
    assert by_id["domain_expansion"]["sample_count"] == 1
    assert by_id["domain_expansion"]["reason"] == "below_min_samples"

    included = {pose["pose_id"] for pose in manifest["poses"]}  # type: ignore[union-attr]
    assert not (included & set(by_id)), "a pose is either included or excluded, never both"


def test_the_payload_length_matches_what_the_manifest_claims() -> None:
    """Offsets are the only thing telling the browser where a pose's hands are."""
    manifest, payload = build_bundle(DATASET)
    landmark_count = manifest["landmark_count"]
    components = manifest["components"]
    total_hands = manifest["total_hands"]
    assert isinstance(landmark_count, int) and isinstance(components, int)
    assert isinstance(total_hands, int)

    assert len(payload) == total_hands * landmark_count * components * 4

    offset = 0
    for pose in manifest["poses"]:  # type: ignore[union-attr]
        assert pose["hand_offset"] == offset
        assert pose["hand_count"] == len(pose["hands"])
        offset += pose["hand_count"]
    assert offset == total_hands


def test_both_matching_paths_survive_the_export() -> None:
    """FR-023c: the eligible population keeps at least one pose of each hand requirement.

    Asserted against the generated manifest rather than against a written-down list, so a
    dataset change that removed every one-handed or every two-handed pose fails here
    instead of quietly leaving half the matcher unexercised.
    """
    manifest, _ = build_bundle(DATASET)
    requirements = {pose["required_hands"] for pose in manifest["poses"]}  # type: ignore[union-attr]
    assert 1 in requirements
    assert 2 in requirements
