/**
 * The canonical pose-sample serializer — a cross-language port of Engine's `PoseSerializer`
 * (contracts/pose-sample-export.md, FR-029 – FR-035, FR-063).
 *
 * Mudra Web writes Engine's schema v1 **exactly**. It is not a Web-specific format, not a variant,
 * and not a second landmark representation. Its faithfulness is not asserted in prose:
 * `test/domain/pose-sample-serializer.test.ts` compares it against fixtures generated by Engine's
 * own implementation, key order included, and the constitution is explicit that a port which cannot
 * be checked that way **is not authorized**.
 *
 * Three things this file does deliberately, each recorded in the contract:
 *
 * * **Key order is Engine's**, because JavaScript preserves object insertion order for the
 *   non-integer string keys this schema uses, which is what makes key order comparable at all.
 * * **Four additive fields, and no more** — `session_uuid`, `contributor_label`,
 *   `countdown_enabled`, `mirrored_preview` — each inside a block Engine already reads.
 * * **`position` and `lens_facing` are absent.** A browser cannot determine which physical lens is
 *   in use, and an absent optional field is correct where an invented value would be false.
 */

import type { CaptureSample, CaptureSession } from '../../domain/capture/types';
import type { Landmark } from '../../domain/landmarks/types';
import {
  NORMALIZATION_STRATEGY,
  NORMALIZATION_VERSION,
} from '../../domain/normalization/normalize';

/** Schema version Mudra Web writes. Changing it is a cross-application event, never a local edit. */
export const POSE_SAMPLE_SCHEMA_VERSION = 1;

/**
 * `metadata.camera.index`, by stated convention (research D4).
 *
 * Engine looks this key up unconditionally, so it must carry something. Browsers expose no stable,
 * meaningful camera index, so `0` is documented to mean "the default camera this session opened"
 * and carries no other claim.
 */
export const WEB_CAMERA_INDEX = 0;

/** Versions the composition root reads from build-time constants and injects (research D5). */
export interface ApplicationVersions {
  /** Written to the engine-owned `versions.application`, e.g. `mudra-web/0.1.0` (FR-034). */
  readonly application: string;
  /** The detection backend actually used, e.g. `0.10.35`. */
  readonly mediapipe: string;
}

/** Everything one canonical document is built from. */
export interface PoseSampleInput {
  readonly session: CaptureSession;
  readonly sample: CaptureSample;
  /** `sample_NNNNNN`, assigned at export because numbering is a property of the archive. */
  readonly sampleNumber: string;
  readonly versions: ApplicationVersions;
}

/** A serialized landmark, in the schema's own shape. */
interface LandmarkDocument {
  readonly x: number;
  readonly y: number;
  readonly z: number;
}

/** One hand, as the schema carries it. */
interface HandDocument {
  readonly handedness: string;
  readonly confidence: number;
  readonly raw: readonly LandmarkDocument[];
  readonly normalized: readonly LandmarkDocument[];
}

/** The canonical document. Field order here **is** the wire order. */
export interface PoseSampleDocument {
  readonly schema_version: number;
  readonly pose_id: string;
  readonly display_name: string | null;
  readonly description: string | null;
  readonly sample_uuid: string;
  readonly sample_number: string;
  readonly timestamp: string;
  readonly normalization: { readonly strategy: string; readonly version: string };
  readonly metadata: {
    readonly timestamp: string;
    readonly camera: {
      readonly index: number;
      readonly width: number;
      readonly height: number;
      /** Additive: records the coordinate convention of `raw`. Always `true` in a browser. */
      readonly mirrored_preview: boolean;
    };
    readonly versions: { readonly application: string; readonly mediapipe: string };
    readonly num_hands: number;
    readonly hands: readonly { readonly handedness: string; readonly confidence: number }[];
    readonly capture: {
      readonly countdown_start_time: string | null;
      readonly capture_time: string;
      readonly countdown_seconds: number;
      /** Additive: distinguishes "no countdown" from "a countdown of zero seconds". */
      readonly countdown_enabled: boolean;
      /** Additive: the recording session that produced this sample. */
      readonly session_uuid: string;
      /** Additive: which collaborator contributed it. Provenance, never identity. */
      readonly contributor_label: string;
    };
  };
  readonly hands: readonly HandDocument[];
}

function landmarks(points: readonly Landmark[]): LandmarkDocument[] {
  return points.map((p) => ({ x: p.x, y: p.y, z: p.z }));
}

/**
 * Serialize one capture sample into the canonical schema-v1 document.
 *
 * Every literal key below appears in Engine's `PoseSerializer.to_dict`, in this order. The two
 * `NORMALIZATION_*` values are read from the normalization module rather than re-typed, so a change
 * to the convention cannot leave the stamp behind.
 */
export function serializePoseSample(input: PoseSampleInput): PoseSampleDocument {
  const { session, sample, sampleNumber, versions } = input;
  return {
    schema_version: POSE_SAMPLE_SCHEMA_VERSION,
    pose_id: session.poseId,
    display_name: session.displayName,
    // Always null: the dataset the browser loads carries no description, and inventing one would
    // be untruthful under FR-030 (FR-014b).
    description: null,
    sample_uuid: sample.id,
    sample_number: sampleNumber,
    timestamp: sample.capturedAt,
    normalization: { strategy: NORMALIZATION_STRATEGY, version: NORMALIZATION_VERSION },
    metadata: {
      timestamp: sample.capturedAt,
      camera: {
        index: WEB_CAMERA_INDEX,
        width: sample.frameWidth,
        height: sample.frameHeight,
        mirrored_preview: true,
      },
      versions: { application: versions.application, mediapipe: versions.mediapipe },
      num_hands: sample.hands.length,
      hands: sample.hands.map((hand) => ({
        handedness: hand.handedness,
        confidence: hand.confidence,
      })),
      capture: {
        countdown_start_time: sample.countdownStartedAt,
        capture_time: sample.capturedAt,
        countdown_seconds: sample.countdownSeconds,
        countdown_enabled: sample.countdownEnabled,
        session_uuid: session.id,
        contributor_label: session.contributorLabel,
      },
    },
    hands: sample.hands.map((hand) => ({
      handedness: hand.handedness,
      confidence: hand.confidence,
      raw: landmarks(hand.raw),
      normalized: landmarks(hand.normalized),
    })),
  };
}

/**
 * Serialize to the JSON text an archive entry holds.
 *
 * Two-space indentation, matching what Engine writes to disk, so a sample extracted from a Mudra Web
 * archive looks like every other sample in the dataset.
 */
export function serializePoseSampleJson(input: PoseSampleInput): string {
  return JSON.stringify(serializePoseSample(input), null, 2);
}

/** `sample_NNNNNN` for a 1-based position within a pose's collection (FR-047). */
export function sampleNumber(position: number): string {
  return 'sample_' + String(position).padStart(6, '0');
}
