/**
 * The translation-scale normalizer — a port of Engine's `TranslationScaleNormalizer`.
 *
 * Web is TypeScript and cannot import Python, so this is a deliberate re-implementation
 * (FR-099) whose faithfulness is not asserted in prose: `test/domain/normalization.test.ts`
 * compares it against fixtures generated by Engine's own implementation, within `1e-9`.
 *
 * What it does: re-origin the hand at the wrist and divide by the wrist-to-middle-MCP
 * span, removing where the hand is in frame and how far it is from the camera while
 * preserving orientation. Rotation is deliberately *not* removed — the dataset was
 * recorded under the same convention, and a pose's rotation is part of its identity.
 */

import type { HandLandmarks, Landmark } from '../landmarks/types';
import { handLandmarks } from '../landmarks/types';
import { MIDDLE_FINGER_MCP, WRIST } from '../landmarks/topology';

/** Identifies the convention the coordinates end up in; stamped into the bundle. */
export const NORMALIZATION_STRATEGY = 'translation_scale';

/** Version of that convention. A change here invalidates every exemplar bundle. */
export const NORMALIZATION_VERSION = '1.0';

/**
 * Below this span the hand is treated as collapsed and only translated.
 *
 * Matched to Engine exactly, including the comparison being strictly `<`: a port that
 * used `<=` or a different epsilon would diverge only on hands that look fine, which is
 * why `tiny_span` is one of the golden fixture cases.
 */
export const DEGENERATE_SPAN = 1e-9;

/**
 * Return a translated and uniformly scaled copy of `hand`.
 *
 * The wrist lands exactly on `(0,0,0)`. A ~zero span falls back to a scale of 1.0
 * (translation only) rather than dividing by zero.
 */
export function normalize(hand: HandLandmarks): HandLandmarks {
  const origin = hand.points[WRIST];
  const reference = hand.points[MIDDLE_FINGER_MCP];
  if (origin === undefined || reference === undefined) {
    // Unreachable while HandLandmarks enforces 21 points; noUncheckedIndexedAccess makes
    // the guarantee explicit rather than implicit.
    throw new Error('normalize requires a hand with wrist and middle-finger MCP present.');
  }

  const dx = reference.x - origin.x;
  const dy = reference.y - origin.y;
  const dz = reference.z - origin.z;
  let span = Math.sqrt(dx * dx + dy * dy + dz * dz);
  if (span < DEGENERATE_SPAN) {
    span = 1;
  }

  const points: Landmark[] = hand.points.map((p) => ({
    x: (p.x - origin.x) / span,
    y: (p.y - origin.y) / span,
    z: (p.z - origin.z) / span,
  }));
  return handLandmarks(points);
}
