"""Generate golden fixtures for the Mudra Web TypeScript test suite.

Mudra Web re-implements the engine's normalization and its nearest-neighbour matching in
TypeScript, because it is a browser application and cannot import Python (FR-098,
FR-099). The constitution requires such a port be verified against fixtures generated by
the reference implementation rather than against hand-written expectations, so this script
writes Engine's real output to ``apps/web/test/fixtures/``.

It is the same position and the same justification as the existing
``scripts/export_capture_fixtures.py``: a repository-level build script, run under Python,
whose output is data. No Engine symbol enters ``apps/web/``.

Run from the repository root::

    python scripts/export_web_fixtures.py

Two suites, two tolerances (research D5):

* ``normalization_cases.json`` — compared within ``1e-9`` absolute. JavaScript numbers are
  IEEE-754 doubles, so agreement here should be near machine precision and a loose
  tolerance would hide a real bug.
* ``matcher_cases.json`` — compared within ``1e-5`` relative. Exemplars in the browser are
  ``float32`` (the bundle format), so the reference below is computed over the *same*
  quantized values: the comparison is against what the browser actually holds, not an
  idealized version of it.

The matcher suite reads ``datasets/poses/`` **read-only**, through Engine's own
repository. It never writes there.
"""

from __future__ import annotations

import json
import math
import struct
from pathlib import Path

from engine.config.models import DatasetConfig, NormalizationConfig
from engine.dataset.json_repository import JsonPoseRepository
from engine.dataset.repository import PoseRepositoryError
from engine.dataset.serializer import PoseSchemaError, PoseSerializer
from engine.models.landmarks import HandLandmarks, Landmark
from engine.models.topology import HAND_LANDMARK_COUNT, LandmarkIndex
from engine.normalization.translation_scale import TranslationScaleNormalizer

REPO_ROOT = Path(__file__).resolve().parents[1]
FIXTURES = REPO_ROOT / "apps" / "web" / "test" / "fixtures"

#: Poses the matcher fixture is built from. Deliberately small, deliberately mixed: two
#: one-handed and two two-handed, so both matching paths are covered by golden data and
#: not only by hand-written unit tests.
FIXTURE_POSES: tuple[str, ...] = ("hi", "peace", "tp", "dragon")

#: Exemplars kept per pose. Small enough that the fixture stays reviewable, large enough
#: that the nearest neighbour is a real choice rather than a foregone one.
EXEMPLARS_PER_POSE = 6

#: Per-landmark weights the port must agree with: wrist 0.5, fingertips 2.0, rest 1.0.
FINGERTIPS = (4, 8, 12, 16, 20)


def landmark_weights() -> list[float]:
    """Return the default 21 per-landmark distance weights."""
    weights = [1.0] * HAND_LANDMARK_COUNT
    weights[LandmarkIndex.WRIST] = 0.5
    for tip in FINGERTIPS:
        weights[tip] = 2.0
    return weights


# --------------------------------------------------------------------------- #
# Synthetic hands
# --------------------------------------------------------------------------- #


def _linear_hand(offset: float = 0.0, scale: float = 1.0) -> HandLandmarks:
    """A straight-line hand — the simplest reproducible shape."""
    return HandLandmarks(
        points=tuple(
            Landmark(
                x=offset + scale * (0.01 * i),
                y=offset + scale * (0.02 * i),
                z=scale * (0.005 * i),
            )
            for i in range(HAND_LANDMARK_COUNT)
        )
    )


def _spiral_hand(phase: float = 0.0) -> HandLandmarks:
    """A curved hand, so normalization parity is not tested only on a straight line."""
    return HandLandmarks(
        points=tuple(
            Landmark(
                x=0.5 + 0.12 * math.cos(i * 0.7 + phase),
                y=0.5 + 0.09 * math.sin(i * 0.9 + phase),
                z=-0.03 + 0.004 * i,
            )
            for i in range(HAND_LANDMARK_COUNT)
        )
    )


def _degenerate_hand() -> HandLandmarks:
    """All points coincident: exercises the ~zero-span fallback (scale = 1.0)."""
    return HandLandmarks(
        points=tuple(Landmark(x=0.25, y=0.75, z=0.0) for _ in range(HAND_LANDMARK_COUNT))
    )


def _tiny_span_hand() -> HandLandmarks:
    """A hand whose wrist-to-MCP span sits just *above* the fallback threshold.

    The interesting case is not the degenerate one — it is the one immediately beside it,
    where a port that used a different comparison (``<=`` instead of ``<``, or a different
    epsilon) would diverge without ever looking degenerate.
    """
    points = [Landmark(x=0.4, y=0.4, z=0.0) for _ in range(HAND_LANDMARK_COUNT)]
    points[LandmarkIndex.MIDDLE_MCP] = Landmark(x=0.4 + 1e-8, y=0.4, z=0.0)
    return HandLandmarks(points=tuple(points))


def _negative_z_hand() -> HandLandmarks:
    """Depth values on both sides of zero, since ``z`` participates in the span."""
    return HandLandmarks(
        points=tuple(
            Landmark(
                x=0.5 - 0.01 * i,
                y=0.2 + 0.03 * i,
                z=0.05 - 0.01 * i,
            )
            for i in range(HAND_LANDMARK_COUNT)
        )
    )


def _landmarks_to_list(hand: HandLandmarks) -> list[dict[str, float]]:
    return [{"x": p.x, "y": p.y, "z": p.z} for p in hand.points]


# --------------------------------------------------------------------------- #
# Suite 1 — normalization
# --------------------------------------------------------------------------- #


def write_normalization_fixture(normalizer: TranslationScaleNormalizer) -> None:
    """Write raw/normalized landmark pairs for the TypeScript port to reproduce."""
    cases = {
        "linear": _linear_hand(),
        "offset_scaled": _linear_hand(offset=0.3, scale=2.5),
        "spiral": _spiral_hand(),
        "spiral_phase": _spiral_hand(phase=1.1),
        "negative_z": _negative_z_hand(),
        "tiny_span": _tiny_span_hand(),
        "degenerate_span": _degenerate_hand(),
    }
    payload = {
        "strategy": normalizer.strategy,
        "version": normalizer.version,
        "origin_index": int(LandmarkIndex.WRIST),
        "scale_index": int(LandmarkIndex.MIDDLE_MCP),
        "tolerance": 1e-9,
        "cases": [
            {
                "name": name,
                "raw": _landmarks_to_list(hand),
                "normalized": _landmarks_to_list(normalizer.normalize(hand)),
            }
            for name, hand in cases.items()
        ],
    }
    path = FIXTURES / "normalization_cases.json"
    path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {path.relative_to(REPO_ROOT)} ({len(cases)} cases)")


# --------------------------------------------------------------------------- #
# Suite 2 — matching
# --------------------------------------------------------------------------- #


def _quantize(hand: HandLandmarks) -> tuple[tuple[float, float, float], ...]:
    """Round a hand's coordinates to float32, exactly as the bundle stores them.

    The browser never sees float64 exemplars, so a reference computed over float64 would
    be comparing the port against something that does not exist (research D4/D5).
    """
    return tuple(
        struct.unpack("<3f", struct.pack("<3f", p.x, p.y, p.z)) for p in hand.points
    )


def _weighted_distance(
    live: tuple[tuple[float, float, float], ...],
    exemplar: tuple[tuple[float, float, float], ...],
    weights: list[float],
) -> float:
    """Squared weighted distance — the ranking is identical to the rooted form."""
    total = 0.0
    for i, weight in enumerate(weights):
        lx, ly, lz = live[i]
        ex, ey, ez = exemplar[i]
        total += weight * ((lx - ex) ** 2 + (ly - ey) ** 2 + (lz - ez) ** 2)
    return total


def _softmax(distances: list[float], temperature: float) -> list[float]:
    """Max-subtracted softmax over negated distances (FR-025)."""
    scores = [-d / temperature for d in distances]
    top = max(scores)
    exponentials = [math.exp(s - top) for s in scores]
    total = sum(exponentials)
    return [e / total for e in exponentials]


def _load_pose_hands(
    repository: JsonPoseRepository,
    poses_root: Path,
    pose_id: str,
    limit: int,
) -> list[dict[str, object]]:
    """Load the first ``limit`` samples of a pose in sorted filename order.

    Read-only: the repository's ``load_path`` is the only method touched, per
    contracts/engine-consumption.md.
    """
    pose_dir = poses_root / pose_id
    samples: list[dict[str, object]] = []
    for path in sorted(pose_dir.glob("sample_*.json"))[:limit]:
        try:
            sample = repository.load_path(path)
        except (PoseRepositoryError, PoseSchemaError) as error:  # pragma: no cover
            print(f"  skipped {path.name}: {error}")
            continue
        samples.append(
            {
                "sample_id": sample.sample_number or sample.sample_uuid,
                "hands": [
                    {
                        "handedness": str(hand.handedness),
                        "landmarks": _quantize(hand.normalized),
                    }
                    for hand in sample.hands
                ],
            }
        )
    return samples


def _match_one_handed(
    live: tuple[tuple[float, float, float], ...],
    exemplars: list[dict[str, object]],
    weights: list[float],
) -> float:
    """Hand-agnostic: any live hand against any exemplar hand of the pose (FR-021)."""
    best = math.inf
    for sample in exemplars:
        for hand in sample["hands"]:  # type: ignore[index]
            best = min(best, _weighted_distance(live, hand["landmarks"], weights))
    return best


def _match_two_handed(
    live_hands: list[dict[str, object]],
    exemplars: list[dict[str, object]],
    weights: list[float],
) -> float:
    """Like-for-like within one ``sample_id``, combined as the **mean** (FR-022, FR-023)."""
    best = math.inf
    for sample in exemplars:
        sample_hands = sample["hands"]  # type: ignore[index]
        if len(sample_hands) < 2 or len(live_hands) < 2:
            continue
        for order in ((0, 1), (1, 0)):
            total = 0.0
            ok = True
            for live, index in zip(live_hands, order, strict=True):
                exemplar = sample_hands[index]
                if exemplar["handedness"] != live["handedness"]:
                    ok = False
                    break
                total += _weighted_distance(live["landmarks"], exemplar["landmarks"], weights)
            if ok:
                best = min(best, total / len(live_hands))
    return best


def write_matcher_fixture(dataset_root: Path) -> None:
    """Write matcher reference cases computed over float32-quantized exemplars."""
    config = DatasetConfig(root=str(dataset_root))
    repository = JsonPoseRepository(config, PoseSerializer())
    poses_root = dataset_root / config.poses_dirname
    weights = landmark_weights()
    temperature = 0.35

    exemplars: dict[str, list[dict[str, object]]] = {}
    required_hands: dict[str, int] = {}
    for pose_id in FIXTURE_POSES:
        samples = _load_pose_hands(repository, poses_root, pose_id, EXEMPLARS_PER_POSE + 2)
        if not samples:
            raise SystemExit(f"No samples found for fixture pose {pose_id!r} under {poses_root}")
        required_hands[pose_id] = len(samples[0]["hands"])  # type: ignore[arg-type]
        exemplars[pose_id] = samples

    # The last two samples of each pose are held out as probes, so a probe is never its
    # own nearest neighbour — a fixture where distance 0 is always the answer proves
    # nothing about ranking.
    probes: list[dict[str, object]] = []
    for pose_id in FIXTURE_POSES:
        for sample in exemplars[pose_id][EXEMPLARS_PER_POSE:]:
            probes.append({"source_pose_id": pose_id, "sample": sample})
        exemplars[pose_id] = exemplars[pose_id][:EXEMPLARS_PER_POSE]

    cases: list[dict[str, object]] = []
    for probe in probes:
        live_hands = probe["sample"]["hands"]  # type: ignore[index]
        candidates: list[dict[str, object]] = []
        for pose_id in FIXTURE_POSES:
            if required_hands[pose_id] > len(live_hands):
                continue  # ineligible: not enough hands in frame (FR-024)
            if required_hands[pose_id] == 1:
                distance = min(
                    _match_one_handed(hand["landmarks"], exemplars[pose_id], weights)
                    for hand in live_hands
                )
            else:
                distance = _match_two_handed(live_hands, exemplars[pose_id], weights)
            if math.isinf(distance):
                continue
            candidates.append({"pose_id": pose_id, "distance": distance})

        candidates.sort(key=lambda c: (c["distance"], c["pose_id"]))
        confidences = _softmax([float(c["distance"]) for c in candidates], temperature)
        for candidate, confidence in zip(candidates, confidences, strict=True):
            candidate["confidence"] = confidence

        cases.append(
            {
                "name": f"{probe['source_pose_id']}::{probe['sample']['sample_id']}",  # type: ignore[index]
                "source_pose_id": probe["source_pose_id"],
                "hands": [
                    {
                        "handedness": hand["handedness"],
                        "landmarks": [list(p) for p in hand["landmarks"]],
                    }
                    for hand in live_hands
                ],
                "candidates": candidates,
            }
        )

    payload = {
        "tolerance_relative": 1e-5,
        "softmax_temperature": temperature,
        "weights": weights,
        "poses": [
            {
                "pose_id": pose_id,
                "required_hands": required_hands[pose_id],
                "exemplars": [
                    {
                        "sample_id": sample["sample_id"],
                        "hands": [
                            {
                                "handedness": hand["handedness"],
                                "landmarks": [list(p) for p in hand["landmarks"]],
                            }
                            for hand in sample["hands"]  # type: ignore[index]
                        ],
                    }
                    for sample in exemplars[pose_id]
                ],
            }
            for pose_id in FIXTURE_POSES
        ],
        "cases": cases,
    }

    path = FIXTURES / "matcher_cases.json"
    path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    print(
        f"wrote {path.relative_to(REPO_ROOT)} "
        f"({len(FIXTURE_POSES)} poses, {len(cases)} probe cases)"
    )


def main() -> None:
    """Generate every fixture the TypeScript suite compares against."""
    FIXTURES.mkdir(parents=True, exist_ok=True)
    normalizer = TranslationScaleNormalizer(NormalizationConfig())

    write_normalization_fixture(normalizer)

    dataset_root = REPO_ROOT / "datasets"
    if (dataset_root / "poses").is_dir():
        write_matcher_fixture(dataset_root)
    else:  # pragma: no cover - only reachable on a checkout without the dataset
        raise SystemExit(
            f"Dataset not found at {dataset_root / 'poses'}. The matcher fixtures are "
            "generated from recorded samples and cannot be synthesized."
        )

    print(f"\nFixtures written to {FIXTURES.resolve()}")
    print("apps/web/test/domain/ asserts parity against these files.")


if __name__ == "__main__":
    main()
